### ISSUE TITLE
Supports Go language

### ISSUE THREAD

**Issue by mingrammer** [parkjs814/DuoCoder#4]
Do you have plans for supporting the Go language now? If not, I want to add Go features.

**Comment by 64json** [comment]
Any programming language in the world is very welcome :)

**Comment by utilForever** [comment]
I'll work with you. Welcome 👏

**Comment by mingrammer** [comment]
Sorry for late. I'll send a PR to support Go in this month.

**Comment by mingrammer** [comment]
@parkjs814 The end of last year was so busy. I'm working on supporting the Go now.

So I need logos (both colored and mono ones) for Go like other languages, could you tell me where you made the logos?

**Comment by 64json** [comment]
You may google the official logo of the language and resize it so that Math.max(logo.width, logo.height) === 512. Thanks!

**Comment by mingrammer** [comment]
I close it
